#!/usr/bin/env bash
mode=debug
for i in "$@"; do
	case "$i" in
		backtrace) export RUST_BACKTRACE=1;;
		full) export RUST_BACKTRACE=full;;
		release) mode=$i;;
	esac
done
"./target/$mode/rust-dungeon-crawler"
