#!/usr/bin/env bash
exec > project.md
# shellcheck disable=SC2016
printf '# Thoughts?\n```tree\n%s\n```\n' "$(tree src --dirsfirst --noreport -F)"
while read -r f; do
	# shellcheck disable=SC2016
	printf '## `%s`\n```%s\n%s\n```\n' "${f#src/}" "${f##*.}" "$(<"$f")"
done < <(find src -type f | sort)
